---
name: AdvancedEnderBult
version: 1.0.0
api: 4.0.0
main: Zwuiix\AdvancedEnderBult\Main
authors:
- Zwuiix
permissions:
  advancedenderbult.enderbult:
    default: op
    description: Allow usage of all EnderBult features
description: Loaded by FolderPluginLoader
github: https://github.com/Zwuiix-cmd
loader:
  name: FolderPluginLoader
  main: Zwuiix\Main
  version: 1.0.0
  api:
  - 4.0.0
  authors:
  - Zwuiix
  - pmmp
...
